(function() {var implementors = {};
implementors["byteorder"] = [{"text":"impl Ord for BigEndian","synthetic":false,"types":[]},{"text":"impl Ord for LittleEndian","synthetic":false,"types":[]}];
implementors["generic_array"] = [{"text":"impl&lt;T:&nbsp;Ord, N&gt; Ord for GenericArray&lt;T, N&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;N: ArrayLength&lt;T&gt;,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["gimli"] = [{"text":"impl Ord for Register","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Ord&gt; Ord for DebugInfoOffset&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Ord&gt; Ord for DebugTypesOffset&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Ord&gt; Ord for UnitSectionOffset&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl Ord for SectionId","synthetic":false,"types":[]},{"text":"impl Ord for DwUt","synthetic":false,"types":[]},{"text":"impl Ord for DwCfa","synthetic":false,"types":[]},{"text":"impl Ord for DwChildren","synthetic":false,"types":[]},{"text":"impl Ord for DwTag","synthetic":false,"types":[]},{"text":"impl Ord for DwAt","synthetic":false,"types":[]},{"text":"impl Ord for DwForm","synthetic":false,"types":[]},{"text":"impl Ord for DwAte","synthetic":false,"types":[]},{"text":"impl Ord for DwLle","synthetic":false,"types":[]},{"text":"impl Ord for DwDs","synthetic":false,"types":[]},{"text":"impl Ord for DwEnd","synthetic":false,"types":[]},{"text":"impl Ord for DwAccess","synthetic":false,"types":[]},{"text":"impl Ord for DwVis","synthetic":false,"types":[]},{"text":"impl Ord for DwVirtuality","synthetic":false,"types":[]},{"text":"impl Ord for DwLang","synthetic":false,"types":[]},{"text":"impl Ord for DwAddr","synthetic":false,"types":[]},{"text":"impl Ord for DwId","synthetic":false,"types":[]},{"text":"impl Ord for DwCc","synthetic":false,"types":[]},{"text":"impl Ord for DwInl","synthetic":false,"types":[]},{"text":"impl Ord for DwOrd","synthetic":false,"types":[]},{"text":"impl Ord for DwDsc","synthetic":false,"types":[]},{"text":"impl Ord for DwIdx","synthetic":false,"types":[]},{"text":"impl Ord for DwDefaulted","synthetic":false,"types":[]},{"text":"impl Ord for DwLns","synthetic":false,"types":[]},{"text":"impl Ord for DwLne","synthetic":false,"types":[]},{"text":"impl Ord for DwLnct","synthetic":false,"types":[]},{"text":"impl Ord for DwMacro","synthetic":false,"types":[]},{"text":"impl Ord for DwRle","synthetic":false,"types":[]},{"text":"impl Ord for DwOp","synthetic":false,"types":[]},{"text":"impl Ord for DwEhPe","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Copy + Ord&gt; Ord for ArangeEntry&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl Ord for ColumnType","synthetic":false,"types":[]},{"text":"impl&lt;T:&nbsp;Ord&gt; Ord for UnitOffset&lt;T&gt;","synthetic":false,"types":[]}];
implementors["libsignal_protocol"] = [{"text":"impl Ord for Buffer","synthetic":false,"types":[]},{"text":"impl Ord for PrivateKey","synthetic":false,"types":[]},{"text":"impl Ord for PublicKey","synthetic":false,"types":[]}];
implementors["log"] = [{"text":"impl Ord for Level","synthetic":false,"types":[]},{"text":"impl Ord for LevelFilter","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Ord for Metadata&lt;'a&gt;","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Ord for MetadataBuilder&lt;'a&gt;","synthetic":false,"types":[]}];
implementors["object"] = [{"text":"impl&lt;E:&nbsp;Ord + Endian&gt; Ord for U16Bytes&lt;E&gt;","synthetic":false,"types":[]},{"text":"impl&lt;E:&nbsp;Ord + Endian&gt; Ord for U32Bytes&lt;E&gt;","synthetic":false,"types":[]},{"text":"impl&lt;E:&nbsp;Ord + Endian&gt; Ord for U64Bytes&lt;E&gt;","synthetic":false,"types":[]},{"text":"impl&lt;E:&nbsp;Ord + Endian&gt; Ord for I16Bytes&lt;E&gt;","synthetic":false,"types":[]},{"text":"impl&lt;E:&nbsp;Ord + Endian&gt; Ord for I32Bytes&lt;E&gt;","synthetic":false,"types":[]},{"text":"impl&lt;E:&nbsp;Ord + Endian&gt; Ord for I64Bytes&lt;E&gt;","synthetic":false,"types":[]}];
implementors["proc_macro2"] = [{"text":"impl Ord for Ident","synthetic":false,"types":[]}];
implementors["syn"] = [{"text":"impl Ord for Lifetime","synthetic":false,"types":[]}];
implementors["typenum"] = [{"text":"impl Ord for B0","synthetic":false,"types":[]},{"text":"impl Ord for B1","synthetic":false,"types":[]},{"text":"impl&lt;U:&nbsp;Ord + Unsigned + NonZero&gt; Ord for PInt&lt;U&gt;","synthetic":false,"types":[]},{"text":"impl&lt;U:&nbsp;Ord + Unsigned + NonZero&gt; Ord for NInt&lt;U&gt;","synthetic":false,"types":[]},{"text":"impl Ord for Z0","synthetic":false,"types":[]},{"text":"impl Ord for UTerm","synthetic":false,"types":[]},{"text":"impl&lt;U:&nbsp;Ord, B:&nbsp;Ord&gt; Ord for UInt&lt;U, B&gt;","synthetic":false,"types":[]},{"text":"impl Ord for ATerm","synthetic":false,"types":[]},{"text":"impl&lt;V:&nbsp;Ord, A:&nbsp;Ord&gt; Ord for TArr&lt;V, A&gt;","synthetic":false,"types":[]},{"text":"impl Ord for Greater","synthetic":false,"types":[]},{"text":"impl Ord for Less","synthetic":false,"types":[]},{"text":"impl Ord for Equal","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()